export const USER_ERROR_CODE = {
  NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_DUPLICATED: "USER_EMAIL_DUPLICATED",
  NICKNAME_DUPLICATED: "USER_NICKNAME_DUPLICATED",
  FORBIDDEN: "USER_FORBIDDEN",
  DELETED: "USER_DELETED",
  SUSPENDED: "USER_SUSPENDED",
  BANNED: "USER_BANNED",
} as const;

export type UserErrorCode =
  (typeof USER_ERROR_CODE)[keyof typeof USER_ERROR_CODE];
